./Calc2/arx_core/src/include/BranchTypes.sv
./include/IALUTypes.sv
./include/LoadStoreTypes.sv
./include/InstrTypes.sv
./ExecStage.sv
./InsnDecoder.sv
./InsnDecodeStage.sv
./InsnFetch.sv
./LoadStoreUnit.sv
./MemStage.sv
./RegisterFile.sv
./WriteBackStage.sv